export const PAYMENT_SEND_REQUEST = 'payment/PAYMENT_SEND_REQUEST'
export const PAYMENT_SEND_SUCCESS = 'payment/PAYMENT_SEND_SUCCESS'
export const PAYMENT_SEND_FAILURE = 'payment/PAYMENT_SEND_FAILURE'

export const PAYMENT_LIST_REQUEST = 'payment/PAYMENT_LIST_REQUEST'
export const PAYMENT_LIST_SUCCESS = 'payment/PAYMENT_LIST_SUCCESS'
export const PAYMENT_LIST_FAILURE = 'payment/PAYMENT_LIST_FAILURE'
