export const PAYMENT_SEND_REQUEST = 'payment/PAYMENT_SEND_REQUEST'
export const PAYMENT_SEND_SUCCESS = 'payment/PAYMENT_SEND_SUCCESS'
export const PAYMENT_SEND_FAILURE = 'payment/PAYMENT_SEND_FAILURE'
