export const TRADE_STELLAR_ORDER_BOOK_REQUEST = 'trade/TRADE_STELLAR_ORDER_BOOK_REQUEST'
export const TRADE_STELLAR_ORDER_BOOK_SUCCESS = 'trade/TRADE_STELLAR_ORDER_BOOK_SUCCESS'
export const TRADE_STELLAR_ORDER_BOOK_FAILURE = 'trade/TRADE_STELLAR_ORDER_BOOK_FAILURE'

export const TRADE_STELLAR_REQUEST = 'trade/TRADE_STELLAR_REQUEST'
export const TRADE_STELLAR_SUCCESS = 'trade/TRADE_STELLAR_SUCCESS'
export const TRADE_STELLAR_FAILURE = 'trade/TRADE_STELLAR_FAILURE'

export const TRADE_STELLAR_OPEN_ORDERS_REQUEST = 'trade/TRADE_STELLAR_OPEN_ORDERS_REQUEST'
export const TRADE_STELLAR_OPEN_ORDERS_SUCCESS = 'trade/TRADE_STELLAR_OPEN_ORDERS_SUCCESS'
export const TRADE_STELLAR_OPEN_ORDERS_FAILURE = 'trade/TRADE_STELLAR_OPEN_ORDERS_FAILURE'
