export const EXCHANGE_DIRECTORY_REQUEST = 'lists/EXCHANGE_DIRECTORY_REQUEST'
export const EXCHANGE_DIRECTORY_SUCCESS = 'lists/EXCHANGE_DIRECTORY_SUCCESS'
export const EXCHANGE_DIRECTORY_FAILURE = 'lists/EXCHANGE_DIRECTORY_FAILURE'