export const MARKET_STELLAR_INFO_REQUEST = 'market/MARKET_STELLAR_INFO_REQUEST'
export const MARKET_STELLAR_INFO_SUCCESS = 'market/MARKET_STELLAR_INFO_SUCCESS'
export const MARKET_STELLAR_INFO_FAILURE = 'market/MARKET_STELLAR_INFO_FAILURE'